name: crud
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-218.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  page_transition: ^2.1.0
  flutter_svg: ^2.0.10+1
  auto_size_text: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animate_text: ^1.0.0
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Nirmala
      fonts:
        - asset: assets/fonts/Nirmala.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
