// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd7bbGLSpYGLGVkTEq-A9pAG3tvcSVZsA',
    appId: '1:377501889467:web:fa55478084bc731df84a9e',
    messagingSenderId: '377501889467',
    projectId: 'crud-71579',
    authDomain: 'crud-71579.firebaseapp.com',
    storageBucket: 'crud-71579.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsEh5PqCRQgAmLePK4Bh5KzWc6QYcV0T4',
    appId: '1:377501889467:ios:ec2507b6545ba096f84a9e',
    messagingSenderId: '377501889467',
    projectId: 'crud-71579',
    storageBucket: 'crud-71579.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsEh5PqCRQgAmLePK4Bh5KzWc6QYcV0T4',
    appId: '1:377501889467:ios:ec2507b6545ba096f84a9e',
    messagingSenderId: '377501889467',
    projectId: 'crud-71579',
    storageBucket: 'crud-71579.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd7bbGLSpYGLGVkTEq-A9pAG3tvcSVZsA',
    appId: '1:377501889467:web:732b11901b2b6195f84a9e',
    messagingSenderId: '377501889467',
    projectId: 'crud-71579',
    authDomain: 'crud-71579.firebaseapp.com',
    storageBucket: 'crud-71579.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1d52XtInbx4jXUI32bKnjNYcIqdaaCEQ',
    appId: '1:377501889467:android:9bca64beb9fbe118f84a9e',
    messagingSenderId: '377501889467',
    projectId: 'crud-71579',
    storageBucket: 'crud-71579.appspot.com',
  );

}